<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

	<ItemGroup>
		<Using Include="Boutique" />
	</ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest" Version="3.6.4" />
  </ItemGroup>



  <ItemGroup>
    <ProjectReference Include="..\BoutiqueClasses\BoutiqueClasses.csproj" />
  </ItemGroup>



  <ItemGroup>
    <Reference Include="BoutiqueClasses">
      <HintPath>..\BoutiqueClasses\bin\Debug\net9.0\BoutiqueClasses.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
