<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AlloCineDAL\AlloCineDAL.csproj" />
		<ProjectReference Include="..\AlloCineInterfaces\AlloCineInterfaces.csproj" />
		<ProjectReference Include="..\AlloCineServiceApi\AlloCineServiceApi.csproj" />
		<ProjectReference Include="..\AlloCineServiceBDD\AlloCineServiceBDD.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
